### ISSUE TITLE
Too big allocation

### ISSUE THREAD

**Issue by andrew-epstein** [pcrain/slippc#15]
Found before your latest changes, so might be fixed already, but I suspect probably not:
```
=================================================================
==15275==ERROR: AddressSanitizer: requested allocation size 0xb58d4c00c6b13340 (0xb58d4c00c6b14340 after adjustments for alignment, red zones etc.) exceeds maximum supported size of 0x10000000000 (thread T0)
    #0 0x102ae4b2d in wrap__Znwm asan_new_delete.cc:130
    #1 0x7fff5b0837b1 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__grow_by_and_replace(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, char const*) (libc++.1.dylib:x86_64+0x37b1)
    #2 0x7fff5b0836e2 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::assign(char const*, unsigned long) (libc++.1.dylib:x86_64+0x36e2)
    #3 0x7fff5b083670 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (libc++.1.dylib:x86_64+0x3670)
    #4 0x1028b3262 in slip::Analyzer::analyze(slip::SlippiReplay const&) analyzer.cpp:701
    #5 0x102924209 in slip::Parser::analyze() parser.cpp:459
    #6 0x1028dcb6f in main main.cpp:64
    #7 0x7fff5e0793d4 in start (libdyld.dylib:x86_64+0x163d4)

==15275==HINT: if you don't care about these errors you may set allocator_may_return_null=1
SUMMARY: AddressSanitizer: allocation-size-too-big asan_new_delete.cc:130 in wrap__Znwm
==15275==ABORTING
Abort trap: 6
```
This will be crash12.slp and I will upload to my fork now.

**Comment by andrew-epstein** [comment]
Just pulled latest changes, I can still reproduce.

**Comment by pcrain** [comment]
Stage ID for the replay in question is 32770, which is way higher than it should ever be. Not sure if the replay is corrupt or what, but problem is an OOB memory access; fixing soon.

**Comment by pcrain** [comment]
Fixed with sanity check to make sure stage id has a name before trying to print the name.
