### ISSUE TITLE
Bus Error

### ISSUE THREAD

**Issue by andrew-epstein** [pcrain/slippc#2]
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==92814==ERROR: AddressSanitizer: BUS on unknown address 0x61a200000026 (pc 0x000102ce02fb bp 0x7ffeecf28e50 sp 0x7ffeecf28ce0 T0)
    #0 0x102ce02fa in slip::Parser::_parseEventDescriptions() parser.cpp:98
    #1 0x102cdd73e in slip::Parser::_parse() parser.cpp:44
    #2 0x102cdcded in slip::Parser::load(char const*) parser.cpp:36
    #3 0x102cd8986 in main main.cpp:28
    #4 0x7fff5e0793d4 in start (libdyld.dylib:x86_64+0x163d4)
```

See more detailed info in #1.

**Comment by pcrain** [comment]
Fixed; see comment in #1
