### ISSUE TITLE
Bus Error #2

### ISSUE THREAD

**Issue by andrew-epstein** [pcrain/slippc#4]
```
$ ./src/slippc -i crashes/crash4.slp -d
Loading crashes/crash4.slp
Parsing header
  Slippi Header Matched
  Raw portion = 25730 bytes
Parsing event descriptions
  Event description length = 13 bytes
  Payload size for event 0x36: 417 bytes
  Payload size for event 0x37: 63 bytes
  Payload size for event 0x38: 37 bytes
  Payload size for event 0x39: 1 bytes
Parsing events proper
  Estimated 125 (+123) frames
  Estimated 125 (+123) frames
  Warning: unknown event code 0x15 encountered
  Warning: unknown event code 0x1 encountered
  Warning: unknown event code 0x42 encountered
  Warning: unknown event code 0xc2 encountered
AddressSanitizer:DEADLYSIGNAL
=================================================================
==97544==ERROR: AddressSanitizer: BUS on unknown address 0x61a200000024 (pc 0x0001028e4278 bp 0x7ffeed326e30 sp 0x7ffeed326d20 T0)
    #0 0x1028e4277 in slip::Parser::_parseEvents() parser.cpp:130
    #1 0x1028df78f in slip::Parser::_parse() parser.cpp:48
    #2 0x1028deded in slip::Parser::load(char const*) parser.cpp:36
    #3 0x1028da986 in main main.cpp:28
    #4 0x7fff5e0793d4 in start (libdyld.dylib:x86_64+0x163d4)
```

See details in #1.

**Comment by pcrain** [comment]
Fixed; see comment in #1
