### ISSUE TITLE
Bus Error

### ISSUE THREAD

**Issue by andrew-epstein** [pcrain/slippc#8]
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==74712==ERROR: AddressSanitizer: BUS on unknown address 0x61a200000082 (pc 0x000108c68656 bp 0x7ffee6fa2df0 sp 0x7ffee6fa2cc0 T0)
    #0 0x108c68655 in slip::Parser::_parseEvents() parser.cpp:143
    #1 0x108c62dae in slip::Parser::_parse() parser.cpp:51
    #2 0x108c6231d in slip::Parser::load(char const*) parser.cpp:39
    #3 0x108c5dd07 in main main.cpp:29
    #4 0x7fff5e0793d4 in start (libdyld.dylib:x86_64+0x163d4)
```
crash8.slp

**Comment by pcrain** [comment]
See comment on #6
